### ISSUE TITLE
Xcode 9 Support

### ISSUE THREAD

**Issue by JakeSc** [appsquickly/Typhoon-Swift-Example#18]
> Unsupported Swift Version
> The targets “PocketForecastTests” and “PocketForecast” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.
> Use Xcode 8.x to migrate the code to Swift 3.

**Comment by jasperblues** [comment]
Should be fixed by #20. can you confirm?
