### ISSUE TITLE
Error in Xcode 6.2  date :2015.4.2   (Apr.)

### ISSUE THREAD

**Issue by brandy2015** [appsquickly/Typhoon-Swift-Example#7]
It's a amazing app. But it crash when one url type was unwrapped. I can not find the error,so I would like you can run it in Xcode 6.2 to find it out . Thank you very much.

**Comment by jasperblues** [comment]
Thanks for reporting. We'll investigate. . . we've had to update the Swift version a few times as the language evolves.

**Comment by sebastianwr** [comment]
@jasperblues I can look into it if you like

**Comment by jasperblues** [comment]
@sebastianwr That would be great. Thanks. Also not that @mowens prepared a 1.2 branch that we can now merge in, since Xcode 6.3 was released the other day.

**Comment by jasperblues** [comment]
I've merged Swift 1.2 (aka Xcode 6.3) branch to master and made this the supported version. AFAIK this obsoletes this issue. . closing. . .
