### ISSUE TITLE
Error in the Swift 1.2 branch using Xcode 6.3

### ISSUE THREAD

**Issue by Vkt0r** [appsquickly/Typhoon-Swift-Example#8]
I've downloaded the project for the branch Swift 1.2 and run it in Xcode 6.3 but I have the following error:

    Initializer does not override a designated initializer from its superclass

In the classes `AddCityViewController` and `WeatherReportView` in the lines 29 and 80 respectively. 

The branch isn't ready yet? 
How can I fix it? 

Thanks in advance.

**Comment by jasperblues** [comment]
So sorry about that, we've been very busy with client work. I've finally fixed those issues and merged the Swift 1.2 branch into master. 

Thanks for reporting.
